window.__noodl_modules = [];
window.Noodl = {
  defineModule: function (m) {
    window.__noodl_modules.push(m);
  },
  deployed: true,
};

window.projectData = {
  settings: {},
  components: [
    {
      name: "/App",
      nodes: [
        {
          id: "3dd60053-5ff4-82d5-92ee-4107840d0d3a",
          type: "NewDbModelProperties",
          parameters: {},
          ports: [],
          children: [],
        },
        {
          id: "bbcd06bc-ae99-8ab3-7875-86898d8b3f38",
          type: "Event Receiver",
          parameters: {},
          ports: [],
          children: [],
        },
        {
          id: "246f9453-a119-ac78-171e-3806cf596ecc",
          type: "Group",
          parameters: {
            alignX: "center",
            width: { value: 100, unit: "vw" },
            height: { value: 100, unit: "vh" },
            styleCss:
              'position:fixed; \ntop:0; left:0; \nbottom:0; \nright:0; \nwidth:100%; \nheight:100%; \nborder:none; \nmargin:0; \npadding:0; \noverflow:hidden; \nz-index:auto;"',
          },
          ports: [],
          children: [
            {
              id: "483048f3-a825-1b76-49c8-5606da85951b",
              type: "Group",
              parameters: {
                flexDirection: "column",
                sizeMode: "explicit",
                height: { value: 40, unit: "px" },
                alignItems: "center",
                paddingTop: { value: 8, unit: "px" },
                paddingLeft: { value: 8, unit: "px" },
                paddingRight: { value: 8, unit: "px" },
                paddingBottom: { value: 8, unit: "px" },
                width: { value: 100, unit: "%" },
              },
              ports: [],
              children: [
                {
                  id: "0151abb1-30e5-2c0f-f24f-7b21867178e4",
                  type: "Group",
                  parameters: {
                    width: { value: 100, unit: "%" },
                    sizeMode: "explicit",
                    alignItems: "flex-start",
                    alignX: "right",
                  },
                  ports: [],
                  children: [],
                },
                {
                  id: "21406c4f-9670-7314-e515-adbe84387ae3",
                  type: "Group",
                  parameters: {
                    alignX: "right",
                    sizeMode: "explicit",
                    width: { value: 320, unit: "px" },
                    marginLeft: { value: 4, unit: "px" },
                    marginRight: { value: 4, unit: "px" },
                    marginTop: { value: 4, unit: "px" },
                  },
                  ports: [],
                  children: [
                    {
                      id: "137a009d-ba4d-078a-628c-1fbd694b1cf9",
                      type: "Group",
                      parameters: {
                        backgroundColor: "#0000007F",
                        alignX: "right",
                        marginTop: { value: 0, unit: "px" },
                        borderRadius: { value: 16, unit: "px" },
                        paddingLeft: { value: 0, unit: "px" },
                        paddingTop: { value: 8, unit: "px" },
                        paddingRight: { value: 0, unit: "px" },
                        paddingBottom: { value: 0, unit: "px" },
                        sizeMode: "contentHeight",
                        marginBottom: { value: 8, unit: "px" },
                      },
                      ports: [],
                      children: [
                        {
                          id: "46aaf7b8-85d7-8a7e-a364-cf513313f72f",
                          type: "Group",
                          parameters: {
                            backgroundColor: "#0000004C",
                            paddingTop: { value: 4, unit: "px" },
                            paddingBottom: { value: 4, unit: "px" },
                            paddingLeft: { value: 8, unit: "px" },
                            paddingRight: { value: 8, unit: "px" },
                            borderRadius: { value: 8, unit: "px" },
                            sizeMode: "contentHeight",
                            marginLeft: { value: 8, unit: "px" },
                            marginRight: { value: 8, unit: "px" },
                            marginBottom: { value: 0, unit: "px" },
                            borderBottomLeftRadius: { value: 0, unit: "px" },
                            borderBottomRightRadius: { value: 0, unit: "px" },
                            flexDirection: "row",
                          },
                          ports: [],
                          children: [
                            {
                              id: "9e5ec257-6a58-b778-6cc4-71dcd6051aa4",
                              type: "Text",
                              parameters: {
                                sizeMode: "contentWidth",
                                textAlignY: "center",
                                text: "Current Intelligence Summary • Congo • June 24, 2015 • .PDF",
                                color: "#FFFFFFB2",
                                fontSize: { value: 8, unit: "px" },
                                height: { value: 16, unit: "px" },
                                marginRight: { value: 16, unit: "px" },
                              },
                              ports: [],
                              children: [],
                            },
                            {
                              id: "bcd715be-15e6-6e59-2545-243a7c12def1",
                              type: "Group",
                              parameters: { flexDirection: "row" },
                              ports: [],
                              children: [
                                {
                                  id: "e10e2d11-7670-aa40-ecc4-7d3fad253530",
                                  type: "net.noodl.controls.textinput",
                                  parameters: {
                                    useLabel: false,
                                    useIcon: true,
                                    iconSourceType: "icon",
                                    placeholder: "<",
                                    sizeMode: "contentHeight",
                                    borderRadius: { value: 8, unit: "px" },
                                    alignX: "center",
                                    marginRight: { value: 2, unit: "px" },
                                    iconSize: { value: 8, unit: "px" },
                                    fontFamily: "ro",
                                    backgroundColor: "#00000054",
                                    placeHolderOpacity: 1,
                                    height: { value: 24, unit: "px" },
                                    fontSize: { value: 12, unit: "px" },
                                    borderStyle: "none",
                                    marginLeft: { value: 0, unit: "px" },
                                    width: { value: 16, unit: "px" },
                                    paddingLeft: { value: 0, unit: "px" },
                                    paddingRight: { value: 0, unit: "px" },
                                    borderTopRightRadius: {
                                      value: 1,
                                      unit: "px",
                                    },
                                    borderBottomRightRadius: {
                                      value: 1,
                                      unit: "px",
                                    },
                                    borderTopLeftRadius: {
                                      value: 2,
                                      unit: "px",
                                    },
                                    borderBottomLeftRadius: {
                                      value: 2,
                                      unit: "px",
                                    },
                                  },
                                  ports: [],
                                  children: [],
                                },
                                {
                                  id: "38dbb272-ebb7-c7fd-f940-f20df2af2295",
                                  type: "net.noodl.controls.textinput",
                                  parameters: {
                                    useLabel: false,
                                    useIcon: true,
                                    iconSourceType: "icon",
                                    placeholder: "1/5",
                                    sizeMode: "contentHeight",
                                    borderRadius: { value: 1, unit: "px" },
                                    alignX: "center",
                                    marginRight: { value: 0, unit: "px" },
                                    iconSize: { value: 6, unit: "px" },
                                    fontFamily: "popins",
                                    backgroundColor: "#0000007F",
                                    placeHolderOpacity: 1,
                                    height: { value: 24, unit: "px" },
                                    fontSize: { value: 12, unit: "px" },
                                    borderStyle: "none",
                                    marginLeft: { value: 0, unit: "px" },
                                    width: { value: 24, unit: "px" },
                                    paddingLeft: { value: 0, unit: "px" },
                                    paddingRight: { value: 0, unit: "px" },
                                  },
                                  ports: [],
                                  children: [],
                                },
                                {
                                  id: "27660693-5ce8-4334-a43d-a96c1bfbe6c9",
                                  type: "net.noodl.controls.textinput",
                                  parameters: {
                                    useLabel: false,
                                    useIcon: true,
                                    iconSourceType: "icon",
                                    placeholder: ">",
                                    sizeMode: "contentHeight",
                                    borderRadius: { value: 8, unit: "px" },
                                    alignX: "right",
                                    marginRight: { value: 8, unit: "px" },
                                    iconSize: { value: 8, unit: "px" },
                                    fontFamily: "popins",
                                    backgroundColor: "#00000082",
                                    placeHolderOpacity: 1,
                                    height: { value: 24, unit: "px" },
                                    fontSize: { value: 12, unit: "px" },
                                    borderStyle: "none",
                                    marginLeft: { value: 2, unit: "px" },
                                    width: { value: 16, unit: "px" },
                                    paddingLeft: { value: 0, unit: "px" },
                                    paddingRight: { value: 0, unit: "px" },
                                    borderBottomLeftRadius: {
                                      value: 1,
                                      unit: "px",
                                    },
                                    borderTopLeftRadius: {
                                      value: 1,
                                      unit: "px",
                                    },
                                    borderBottomRightRadius: {
                                      value: 8,
                                      unit: "px",
                                    },
                                    borderTopRightRadius: {
                                      value: 4,
                                      unit: "px",
                                    },
                                  },
                                  ports: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: "24bc355b-3945-ae5f-aaf9-febd52983270",
                          type: "Group",
                          parameters: { flexDirection: "row" },
                          ports: [],
                          children: [
                            {
                              id: "e1f3dd65-549e-0fc9-b393-2853b9f0bfb6",
                              type: "net.noodl.controls.textinput",
                              parameters: {
                                useLabel: false,
                                useIcon: true,
                                iconSourceType: "icon",
                                placeholder: "Search",
                                sizeMode: "explicit",
                                borderRadius: { value: 8, unit: "px" },
                                alignX: "right",
                                marginRight: { value: 8, unit: "px" },
                                iconSize: { value: 10, unit: "px" },
                                backgroundColor: "#000000",
                                placeHolderOpacity: 1,
                                height: { value: 24, unit: "px" },
                                fontSize: { value: 8, unit: "px" },
                                borderStyle: "none",
                                marginLeft: { value: 8, unit: "px" },
                                iconColor: "#FFFFFF",
                                borderTopLeftRadius: { value: 0, unit: "px" },
                                color: "#FFFFFF",
                                fontFamily: "Arial",
                                borderTopRightRadius: { value: 0, unit: "px" },
                              },
                              ports: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: "7c98fc11-868c-237d-1b10-5d51c42c31a7",
                          type: "Group",
                          parameters: {
                            backgroundColor: "#FFFFFF",
                            paddingLeft: { value: 12, unit: "px" },
                            paddingRight: { value: 8, unit: "px" },
                            paddingTop: { value: 12, unit: "px" },
                            paddingBottom: { value: 8, unit: "px" },
                            height: { value: 128, unit: "px" },
                            borderRadius: { value: 8, unit: "px" },
                            marginBottom: { value: 8, unit: "px" },
                            marginLeft: { value: 8, unit: "px" },
                            marginRight: { value: 8, unit: "px" },
                            marginTop: { value: 8, unit: "px" },
                            sizeMode: "contentHeight",
                          },
                          ports: [],
                          children: [
                            {
                              id: "2144c426-57db-e9ba-7bf8-a6bb2e92c329",
                              type: "Text",
                              parameters: {
                                sizeMode: "explicit",
                                textAlignY: "top",
                                text: "”Premier Lumumba apparently has been unable to marshal significant populace of the Leopoldville area, and his influence is diminishing. ”",
                                color: "#000000",
                                alignY: "top",
                                fontSize: { value: 14, unit: "px" },
                                fontFamily: "fonts/poppins",
                                marginTop: { value: 0, unit: "px" },
                              },
                              ports: [],
                              children: [],
                            },
                            {
                              id: "7a5713f9-ad3b-16bb-b934-ed2636a77ca8",
                              type: "Text",
                              parameters: {
                                sizeMode: "explicit",
                                textAlignY: "top",
                                text: "This Points means he is weak, and there was an opportunity for regime change.",
                                color: "#0000007F",
                                alignY: "top",
                                fontSize: { value: 12, unit: "px" },
                                marginTop: { value: 8, unit: "px" },
                                marginBottom: { value: 8, unit: "px" },
                              },
                              ports: [],
                              children: [],
                            },
                            {
                              id: "5ec60bb8-f116-441b-bf44-3bb16b1080d1",
                              type: "Group",
                              parameters: {
                                flexDirection: "row",
                                alignX: "right",
                                justifyContent: "flex-end",
                                sizeMode: "contentHeight",
                              },
                              ports: [],
                              children: [
                                {
                                  id: "d106fe7b-5d9b-71b1-ffcb-02821226fb12",
                                  type: "Text",
                                  parameters: {
                                    sizeMode: "explicit",
                                    textAlignY: "center",
                                    text: "Home /  All /  Research Project 1",
                                    color: "#0000004C",
                                    alignY: "top",
                                    fontSize: { value: 8, unit: "px" },
                                    marginTop: { value: 0, unit: "px" },
                                    marginBottom: { value: 0, unit: "px" },
                                  },
                                  ports: [],
                                  children: [],
                                },
                                {
                                  id: "e871a4a4-e243-3c70-7c2f-20359d2afb7a",
                                  type: "net.noodl.controls.button",
                                  parameters: {
                                    height: { value: 20, unit: "px" },
                                    backgroundColor: "#0000000C",
                                    color: "#0000007F",
                                    borderRadius: { value: 4, unit: "px" },
                                    alignX: "right",
                                    fontSize: { value: 10, unit: "px" },
                                    label: "Share",
                                    paddingTop: { value: 3, unit: "px" },
                                    borderStyle: "solid",
                                    borderWidth: { value: 0.5, unit: "px" },
                                    borderColor: "#0000001C",
                                    paddingLeft: { value: 16, unit: "px" },
                                    paddingRight: { value: 16, unit: "px" },
                                    marginRight: { value: 4, unit: "px" },
                                  },
                                  ports: [],
                                  children: [],
                                },
                                {
                                  id: "9bd86c3f-7a7e-1b34-9b3a-d01b0833e20d",
                                  type: "net.noodl.controls.button",
                                  parameters: {
                                    height: { value: 20, unit: "px" },
                                    backgroundColor: "#5836F523",
                                    color: "Primary",
                                    borderRadius: { value: 4, unit: "px" },
                                    alignX: "right",
                                    fontSize: { value: 10, unit: "px" },
                                    label: "Save",
                                    paddingTop: { value: 3, unit: "px" },
                                    borderStyle: "solid",
                                    borderWidth: { value: 0.5, unit: "px" },
                                    borderColor: "#7000FF33",
                                    paddingLeft: { value: 16, unit: "px" },
                                    paddingRight: { value: 16, unit: "px" },
                                    marginRight: { value: 4, unit: "px" },
                                  },
                                  ports: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
      connections: [
        {
          sourceId: "e871a4a4-e243-3c70-7c2f-20359d2afb7a",
          sourcePort: "onClick",
          targetId: "3dd60053-5ff4-82d5-92ee-4107840d0d3a",
          targetPort: "store",
        },
      ],
      ports: [],
      roots: ["246f9453-a119-ac78-171e-3806cf596ecc"],
      metadata: {
        canvasSize: { width: "1039px", height: "751px" },
        canvasPos: { x: -236, y: -112 },
      },
    },
  ],
  componentIndex: {},
  routerIndex: { routers: [], pages: [] },
  rootComponent: "/App",
  rootNode: "246f9453-a119-ac78-171e-3806cf596ecc",
  metadata: {
    dbCollections: [
      {
        name: "Projects",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            description: { type: "String", required: false },
            title: { type: "String", required: false },
            projectType: { type: "String", required: false, defaultValue: "" },
            identitiesLinked: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
            reportsLinked: {
              type: "Relation",
              targetClass: "Reports",
              required: false,
            },
            photoUrl: { type: "String", required: false },
            tags: { type: "Relation", targetClass: "Tags", required: false },
            authorIs: {
              type: "Relation",
              targetClass: "_User",
              required: false,
            },
          },
        },
      },
      {
        name: "Reports",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            publishedAt: { type: "Date", required: false },
            deletedAt: { type: "Date", required: false },
            isPublished: {
              type: "Boolean",
              required: false,
              defaultValue: false,
            },
            descriptionShort: { type: "String", required: false },
            descriptionLong: { type: "String", required: false },
            authorIs: {
              type: "Pointer",
              targetClass: "_User",
              required: false,
            },
            photoUrl: { type: "String", required: false },
            contentText: { type: "String", required: false },
            readTime: { type: "String", required: false },
            projectIs: {
              type: "Pointer",
              targetClass: "Projects",
              required: false,
            },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
          },
        },
      },
      {
        name: "Subscribers",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            id_investigators: {
              type: "Pointer",
              targetClass: "_User",
              required: false,
            },
            isUser: { type: "Pointer", targetClass: "_User", required: false },
            email: { type: "String", required: false },
            firstName: { type: "String", required: false },
            LastName: { type: "String", required: false },
          },
        },
      },
      {
        name: "Identities",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            firstName: { type: "String", required: false },
            descriptionShort: { type: "String", required: false },
            parentOf: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
            childOf: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
            siblingOf: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
            descriptionLong: { type: "String", required: false },
            middleNames: { type: "String", required: false },
            photoUrl: { type: "String", required: false },
            lastName: { type: "String", required: false },
            wikipediaOf: { type: "String", required: false },
            eventsOf: {
              type: "Relation",
              targetClass: "Events",
              required: false,
            },
            tagsOf: { type: "Relation", targetClass: "Tags", required: false },
            emailOf: { type: "String", required: false },
            websiteOf: { type: "String", required: false },
            twitterOf: { type: "String", required: false },
            prefix: { type: "String", required: false },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
            filesWithin: {
              type: "Relation",
              targetClass: "Files",
              required: false,
            },
            filesContributorOf: {
              type: "Relation",
              targetClass: "Files",
              required: false,
            },
            fullName: { type: "String", required: false },
            birth: { type: "Date", required: false },
            death: { type: "Date", required: false },
            age: { type: "String", required: false },
            wikiDataUrl: { type: "String", required: false },
            nameKnownAs: { type: "String", required: false },
          },
        },
      },
      {
        name: "Organisations",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            descriptionShort: { type: "String", required: false },
            descriptionLong: { type: "String", required: false },
            foundedBy: {
              type: "Pointer",
              targetClass: "Identities",
              required: false,
            },
            websiteOf: { type: "String", required: false },
            wikipediaOf: { type: "String", required: false },
            acronym: { type: "String", required: false },
            photoUrl: { type: "String", required: false },
            logoUrl: { type: "String", required: false },
            foundedAt: { type: "String", required: false },
            headquarteredAt: { type: "String", required: false },
            tagsOf: { type: "Relation", targetClass: "Tags", required: false },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
            twitterOf: { type: "String", required: false },
          },
        },
      },
      {
        name: "Events",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            endTime: { type: "Date", required: false },
            startTime: { type: "Date", required: false },
            startLocation: { type: "String", required: false },
            title: { type: "String", required: false },
            descriptionShort: { type: "String", required: false },
            descriptionLong: { type: "String", required: false },
            eventType: { type: "String", required: false },
            photoUrl: { type: "String", required: false },
            endLocation: { type: "String", required: false },
            identitiesOf: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
            organisationsOf: {
              type: "Relation",
              targetClass: "Organisations",
              required: false,
            },
            outputsOf: {
              type: "Relation",
              targetClass: "Outputs",
              required: false,
            },
            startDate: { type: "Date", required: false },
            endDate: { type: "Date", required: false },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
            logoUrl: { type: "String", required: false },
          },
        },
      },
      {
        name: "Tags",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            description: { type: "String", required: false },
            isOrganisation: {
              type: "Pointer",
              targetClass: "Organisations",
              required: false,
            },
            isIdentity: {
              type: "Pointer",
              targetClass: "Identities",
              required: false,
            },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
            tagsOf: { type: "Relation", targetClass: "Files", required: false },
          },
        },
      },
      {
        name: "EventTypes",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            imageFile: { type: "File", required: false },
            title: { type: "String", required: false },
            description: { type: "String", required: false },
            type: { type: "String", required: false },
            addedBy: {
              type: "Pointer",
              targetClass: "_User",
              required: false,
              defaultValue: {
                __type: "Pointer",
                className: "_User",
                objectId: "ALgOq0w2ur",
              },
            },
          },
        },
      },
      {
        name: "Programs",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            description: { type: "String", required: false },
            photoUrl: { type: "String", required: false },
            logoUrl: { type: "String", required: false },
            acronym: { type: "String", required: false },
            foundedBy: {
              type: "Pointer",
              targetClass: "_User",
              required: false,
            },
            websiteOf: { type: "String", required: false },
            locatedAt: { type: "String", required: false },
            programOf: {
              type: "Pointer",
              targetClass: "_User",
              required: false,
            },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
          },
        },
      },
      {
        name: "OrganisationRole",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            eventsRelated: {
              type: "Relation",
              targetClass: "Events",
              required: false,
            },
            predominantOf: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
            hiredBy: {
              type: "Pointer",
              targetClass: "Identities",
              required: false,
            },
            organisationIs: {
              type: "Pointer",
              targetClass: "Organisations",
              required: false,
            },
            description: { type: "String", required: false },
            dateEnd: { type: "Date", required: false },
            dateStart: { type: "Date", required: false },
            identityIs: {
              type: "Pointer",
              targetClass: "Identities",
              required: false,
            },
            subordinateOf: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
          },
        },
      },
      {
        name: "Outputs",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            outputType: { type: "String", required: false },
            photoUrl: { type: "String", required: false },
            fromEvent: {
              type: "Pointer",
              targetClass: "_User",
              required: false,
            },
            fromOrganisations: {
              type: "Relation",
              targetClass: "Organisations",
              required: false,
            },
            fromIdentities: { type: "String", required: false },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
            descriptionShort: { type: "String", required: false },
            descriptionLong: { type: "String", required: false },
          },
        },
      },
      {
        name: "Sources",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            descriptionShort: { type: "String", required: false },
            descriptionLong: { type: "String", required: false },
            sourceType: { type: "String", required: false },
            urlBacklink: { type: "String", required: false },
            isOutput: {
              type: "Pointer",
              targetClass: "Outputs",
              required: false,
            },
            file: { type: "File", required: false },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
          },
        },
      },
      {
        name: "Files",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            descriptionShort: { type: "String", required: false },
            descriptionLong: { type: "String", required: false },
            fileType: { type: "String", required: false },
            addedBy: { type: "Pointer", targetClass: "_User", required: false },
            file: { type: "File", required: false },
            photoUrl: { type: "String", required: false },
            logoUrl: { type: "String", required: false },
            backlinkUrl: { type: "String", required: false },
            organisationsOf: {
              type: "Relation",
              targetClass: "Organisations",
              required: false,
            },
            fileSize: { type: "Number", required: false },
            tagsOf: { type: "Relation", targetClass: "Tags", required: false },
            contributorsOf: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
            identitiesWithin: {
              type: "Relation",
              targetClass: "Identities",
              required: false,
            },
          },
        },
      },
      {
        name: "Publication",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            title: { type: "String", required: false },
            description: { type: "String", required: false },
            authorIs: {
              type: "Relation",
              targetClass: "_User",
              required: false,
            },
          },
        },
      },
    ],
    styles: {
      text: {
        "Body Text": {
          fontFamily: "fonts/Roboto/Roboto-Regular.ttf",
          fontSize: { value: "18", unit: "px" },
          color: "#000000",
        },
        "Button Label": {
          fontFamily: "fonts/Roboto/Roboto-Regular.ttf",
          fontSize: { value: "16", unit: "px" },
          color: "#000000",
        },
        "Label Text": {
          fontFamily: "fonts/Roboto/Roboto-Regular.ttf",
          fontSize: { value: "14", unit: "px" },
          color: "#000000",
        },
      },
      colors: {
        Primary: "#5836F5",
        "Light Gray": "#C6C6C6",
        "Dark Gray": "#434B53",
        "Primary Dark": "#3F22B8",
        Dark: "#1F1F1F",
        "Primary Light": "#C9BFFC",
      },
    },
    systemCollections: [
      {
        name: "_Role",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            name: { type: "String" },
            users: { type: "Relation", targetClass: "_User" },
            roles: { type: "Relation", targetClass: "_Role" },
          },
        },
      },
      {
        name: "_User",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            username: { type: "String" },
            password: { type: "String" },
            email: { type: "String" },
            emailVerified: { type: "Boolean" },
            authData: { type: "Object" },
            firstName: { type: "String" },
            lastName: { type: "String" },
            profileImage: { type: "File" },
            reportsLinked: {
              type: "Relation",
              targetClass: "Reports",
              required: false,
            },
            isIdentity: {
              type: "Pointer",
              targetClass: "_User",
              required: false,
            },
            userFiles: {
              type: "Relation",
              targetClass: "Files",
              required: false,
            },
            isInvestigator: {
              type: "Boolean",
              required: false,
              defaultValue: false,
            },
            investigatorDescription: { type: "String", required: false },
            projectsOf: {
              type: "Relation",
              targetClass: "Projects",
              required: false,
            },
            newsletterTitle: { type: "String", required: false },
            newsletterDescription: { type: "String", required: false },
          },
        },
      },
      {
        name: "_Session",
        schema: {
          properties: {
            createdAt: { type: "Date" },
            updatedAt: { type: "Date" },
            restricted: { type: "Boolean" },
            user: { type: "Pointer", targetClass: "_User" },
            installationId: { type: "String" },
            sessionToken: { type: "String" },
            expiresAt: { type: "Date" },
            createdWith: { type: "Object" },
          },
        },
      },
    ],
    cloudservices: {
      instanceId: "fe800f780980423b",
      workspaceId: "7ejhif",
      endpoint: "https://backend.noodl.cloud/7ejhif/fe800f780980423b",
      appId: "fe800f780980423b",
    },
  },
  variants: [
    {
      typename: "net.noodl.controls.button",
      parameters: {
        height: { value: 40, unit: "px" },
        sizeMode: "contentWidth",
        backgroundColor: "Primary",
        iconIconSource: { class: "material-icons", code: "home" },
        iconSize: { value: 22, unit: "px" },
        iconSpacing: { value: 6, unit: "px" },
        borderRadius: { value: 4, unit: "px" },
        textStyle: "Button Label",
        paddingTop: { value: 5, unit: "px" },
        paddingLeft: { value: 24, unit: "px" },
        paddingRight: { value: 24, unit: "px" },
        paddingBottom: { value: 4, unit: "px" },
        color: "#FFFFFF",
        fontFamily: "fonts/Roboto/Roboto-Medium.ttf",
      },
      stateParameters: {
        hover: { backgroundColor: "Primary Dark" },
        pressed: { backgroundColor: "Primary Light", color: "Primary Dark" },
        disabled: { backgroundColor: "Light Gray" },
      },
      stateTransitions: {},
      defaultStateTransitions: {
        neutral: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        hover: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        pressed: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
      },
    },
    {
      typename: "net.noodl.controls.radiobutton",
      parameters: {
        width: { value: 24, unit: "px" },
        height: { value: 24, unit: "px" },
        useLabel: true,
        labeltextStyle: "Label Text",
        borderWidth: { value: 2, unit: "px" },
        value: "0",
        useIcon: false,
        fillColor: "transparent",
        borderColor: "#1F1F1F7F",
        labelfontSize: { value: 16, unit: "px" },
      },
      stateParameters: {
        checked: {
          fillColor: "Primary",
          borderColor: "Primary",
          borderWidth: { value: 2, unit: "px" },
          backgroundColor: "#FFFFFF",
          width: { value: 24, unit: "px" },
          height: { value: 24, unit: "px" },
        },
        hover: {
          backgroundColor: "transparent",
          borderColor: "Primary",
          width: { value: 24, unit: "px" },
          height: { value: 24, unit: "px" },
        },
      },
      stateTransitions: {},
      defaultStateTransitions: {
        neutral: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        hover: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        checked: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
      },
    },
    {
      typename: "Text",
      parameters: { textStyle: "Body Text" },
      stateParameters: {},
      stateTransitions: {},
    },
    {
      typename: "net.noodl.controls.range",
      parameters: {
        thumbColor: "Primary",
        thumbBorderRadius: { value: 100, unit: "%" },
        trackHeight: { value: 4, unit: "px" },
        trackActiveColor: "Primary",
        trackColor: "Primary Light",
        width: { value: 100, unit: "%" },
      },
      stateParameters: {},
      stateTransitions: {},
    },
    {
      typename: "net.noodl.controls.checkbox",
      parameters: {
        width: { value: 24, unit: "px" },
        height: { value: 24, unit: "px" },
        useIcon: false,
        borderWidth: { value: 2, unit: "px" },
        useLabel: true,
        labeltextStyle: "Label Text",
        borderRadius: { value: 2, unit: "px" },
        borderColor: "#0000007F",
        labelfontSize: { value: 16, unit: "px" },
        labelcolor: "Dark",
      },
      stateParameters: {
        checked: {
          useIcon: true,
          iconIconSource: { class: "material-icons", code: "check" },
          backgroundColor: "Primary",
          borderColor: "Primary",
          iconSize: { value: 16, unit: "px" },
        },
        disabled: { opacity: 0.5 },
        hover: { borderColor: "Primary" },
        pressed: {},
      },
      stateTransitions: {},
      defaultStateTransitions: {
        neutral: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        hover: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        checked: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
      },
    },
    {
      typename: "net.noodl.controls.textinput",
      parameters: {
        useLabel: true,
        sizeMode: "explicit",
        height: { value: 40, unit: "px" },
        textStyle: "Body Text",
        borderStyle: "solid",
        borderRadius: { value: 4, unit: "px" },
        borderWidth: { value: 2, unit: "px" },
        borderColor: "#1F1F1F7F",
        labeltextStyle: "Label Text",
        paddingLeft: { value: 8, unit: "px" },
        paddingRight: { value: 8, unit: "px" },
        labelSpacing: { value: 4, unit: "px" },
        placeholder: "Type here",
        labelcolor: "#1F1F1F7F",
        labeltextTransform: "uppercase",
        labelfontSize: { value: 12, unit: "px" },
        labelfontFamily: "fonts/Roboto/Roboto-Medium.ttf",
      },
      stateParameters: {
        hover: {
          labelcolor: "#000000",
          borderColor: "Dark",
          borderStyle: "solid",
        },
        focused: {
          borderColor: "Primary",
          labelcolor: "Primary",
          borderWidth: { value: 2, unit: "px" },
          boxShadowEnabled: false,
          boxShadowColor: "Primary",
          borderStyle: "solid",
        },
        disabled: {
          labelcolor: "Light Gray",
          backgroundColor: "Light Gray",
          borderWidth: { value: 1, unit: "px" },
          borderColor: "Light Gray",
        },
      },
      stateTransitions: {},
      defaultStateTransitions: {
        neutral: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        focused: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
      },
    },
    {
      typename: "net.noodl.controls.options",
      parameters: {
        sizeMode: "explicit",
        height: { value: 40, unit: "px" },
        borderWidth: { value: 2, unit: "px" },
        borderRadius: { value: 4, unit: "px" },
        borderColor: "#1F1F1F7F",
        boxShadowColor: "Dark Gray",
        useIcon: true,
        iconIconSource: { class: "material-icons", code: "expand_more" },
        iconPlacement: "right",
        iconSize: { value: 24, unit: "px" },
        paddingRight: { value: 8, unit: "px" },
        textStyle: "Body Text",
        paddingLeft: { value: 8, unit: "px" },
        marginTop: { value: 24, unit: "px" },
        width: { value: 75, unit: "%" },
        iconColor: "#1F1F1F7F",
      },
      stateParameters: {
        hover: {
          borderColor: "Dark",
          borderRadius: { value: 4, unit: "px" },
          iconColor: "Dark",
          iconSize: { value: 24, unit: "px" },
          iconPlacement: "right",
        },
        focused: {
          borderColor: "Primary",
          boxShadowColor: "Primary",
          borderRadius: { value: 4, unit: "px" },
          useIcon: true,
          iconColor: "Primary",
          iconIconSource: {
            class: "material-icons",
            code: "keyboard_arrow_up",
          },
          iconSize: { value: 24, unit: "px" },
          iconPlacement: "right",
        },
        pressed: { borderRadius: { value: 4, unit: "px" } },
      },
      stateTransitions: {},
      defaultStateTransitions: {
        neutral: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
        focused: { curve: [0, 0, 0.58, 1], dur: 300, delay: 0 },
      },
    },
  ],
};
